### Site Settings ###
title               : Emanuele Vivoli
description         : >
                      PhD student @ MICC (UniFI) on Multimodal Learning.
                      Passionated about ⚡ Deep learning 💻 doing stuff and 🌱 Nature
                      :telescope: looking for Ideas!
                      :books: Learning something new every day !
# baseurl             : "/emanuelevivoli.github.io"                 # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
# repository          : emanuelevivoli/emanuelevivoli.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
# remote_theme        : emanuelevivoli/emanuelevivoli.github.io
baseurl             : "/"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : emanuelevivoli/portfolYOU     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : emanuelevivoli/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Emanuele Vivoli
  image             : media/profilo.png
# behance           : your_username
# dribbble          : your_username
  email             : vivoli.emanuele@gmail.com
# facebook          : vivoliemanuele
  github            : emanuelevivoli
# gitlab            : your_username
# instagram         : your_username
  kaggle            : emanuelevivoli
  linkedin          : emanuelevivoli
  medium            : emanuelevivoli
# soundcloud        : your_username
# spotify           : your_username
  stackoverflow     : 10198782
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : emanuelevivoli
# vimeo             : your_username
  youtube           : channel/UC0RQUY3Y-xHkd-3nKsthKaw
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  pubblications:
    output: true
    permalink: /pubblications/:name


### Disqus ###
disqus:
  shortname: emanuelevivoli                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "pubblications"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
